# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K8S_VERSION: v1.12.0
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.31.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true

    working_directory: ~/tf_minikube

    steps:
      - checkout

      - run:
          name: Setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config

      - run:
          name: Setup minikube
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

      - run:
          name: Start minikube
          command: |
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 4096 --kubernetes-version=${K8S_VERSION}

      - run:
          name: Setup terraform
          command: |
            curl '-#' -fL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip"
            unzip -q -d /tmp/ /tmp/terraform.zip
            sudo mv /tmp/terraform /usr/local/bin
            rm -f /tmp/terraform.zip

      - run:
          name: Init terraform
          command: |
            cd terraform && terraform init

      - run:
          name: Plan terraform
          command: |
            cd terraform && terraform plan

      - run:
          name: Apply with terraform
          command: |
            cd terraform && terraform apply -auto-approve -input=false

      - run:
          name: Perform acceptance test
          command:
            ./script/acceptance-test.sh
